### PR TITLE
add remoting

### PR DESCRIPTION
**Pull request by jasonroth**
Added the ability to display data from a remote machine, and to pass alternate credentials if required.

### CODE REVIEW

**Comment by michalmillar** [comment]
Getting the following error:

`The variable '$RemoteSession' cannot be retrieved because it has not been set.
At C:\Users\michael\Documents\WindowsPowerShell\Scripts\Get-MOTD.ps1:76 char:13
+         if ($RemoteSession) {
+             ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (RemoteSession:String) [], Run
   timeException
    + FullyQualifiedErrorId : VariableIsUndefined`

Any thoughts? It looks like it runs through the try, but any time after that, $RemoteSession doesn't exist so it barfs.

**Comment by jasonroth** [comment]
Do you receive this error when run locally or remotely?

Can you run the command with the -verbose parameter, to see if we get more info?

**Comment by michalmillar** [comment]
Hey thanks for asking! I am running it locally with no arguments.

**Comment by jasonroth** [comment]
Does running the command with the verbose switch provide any other details?

**Comment by michalmillar** [comment]
Only for CIM instance information later in the script. The same error output, that I pasted above, is given with or without the verbose flag.

The first error occurs on line 81, which is an if statement:

`if ($RemoteSession) {
    $CommandParams.Add('Session', $RemoteSession)
}`

I think the try statement on line 64 is part of the problem. If I don't use the ComputerName switch, that statement never runs so $RemoteSession is never set. However, if I use the ComputerName switch, I am invoking a connection to a remote host, something I don't want to do if I just want my local machine.

**Pull request merged**
